kafka:
  kafkaBootstrapServers: [localhost:9092]
  pollingTimeout: 10
  consumerGroup: test-consumer-group
  consumerID: test-id
  consumerTopics: [test-topic.1]
  producerTopics: [test-topic.1]
  kafkaSaslJaasConfig: ${SASL_JAAS_CONFIG:org.apache.kafka.common.security.scram.ScramLoginModule required username="client" password="client-secret";}
